// Generated by https://quicktype.io

export interface UsersResponse {
  id: string;
  names: string;
  lastNames: string;
  dniNumber: number;
  email: string;
  cellphone: string;
  address: string;
  note: string;
}
